-- Схема EventLoop. Всё создаётся Flyway; Hibernate работает в режиме validate.

CREATE TABLE app_user (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    max_user_id      BIGINT       NOT NULL UNIQUE,
    chat_id          BIGINT,
    dialog_state     VARCHAR(32)  NOT NULL DEFAULT 'NEW',
    balance_rub      INTEGER      NOT NULL DEFAULT 0 CHECK (balance_rub >= 0),
    cinema_spent_rub INTEGER      NOT NULL DEFAULT 0 CHECK (cinema_spent_rub >= 0),
    origin_name      VARCHAR(128),
    origin_lat       DOUBLE PRECISION,
    origin_lon       DOUBLE PRECISION,
    max_distance_km  INTEGER      NOT NULL DEFAULT 10 CHECK (max_distance_km > 0),
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE user_category (
    user_id  BIGINT      NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    category VARCHAR(32) NOT NULL,
    PRIMARY KEY (user_id, category)
);

-- Инвариант координат: в Москве широта всегда больше долготы (55.7 > 37.6).
-- Ловит одновременно перепутанные местами lat/lon и незаполненные нули —
-- своп даёт правдоподобное, но неверное расстояние, и без констрейнта незаметен.
CREATE TABLE venue (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(255)     NOT NULL UNIQUE,
    address VARCHAR(512)     NOT NULL,
    lat     DOUBLE PRECISION NOT NULL,
    lon     DOUBLE PRECISION NOT NULL,
    CONSTRAINT venue_coords_in_moscow CHECK (lat BETWEEN 55.4 AND 56.1 AND lon BETWEEN 36.9 AND 38.0),
    CONSTRAINT venue_lat_greater_than_lon CHECK (lat > lon)
);

CREATE TABLE event_item (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_key VARCHAR(128)  NOT NULL UNIQUE,
    title        VARCHAR(255)  NOT NULL,
    summary      VARCHAR(512)  NOT NULL,
    category     VARCHAR(32)   NOT NULL,
    age_rating   VARCHAR(8)    NOT NULL,
    venue_id     BIGINT        NOT NULL REFERENCES venue (id),
    poster_url   VARCHAR(1024) NOT NULL,
    event_url    VARCHAR(1024) NOT NULL,
    ticket_url   VARCHAR(1024) NOT NULL
);

CREATE INDEX idx_event_item_category ON event_item (category);

-- Карточка ленты = сеанс, а не мероприятие: только так остаток баланса точен.
CREATE TABLE event_session (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id  BIGINT      NOT NULL REFERENCES event_item (id) ON DELETE CASCADE,
    starts_at TIMESTAMPTZ NOT NULL,
    price_rub INTEGER     NOT NULL CHECK (price_rub > 0),
    CONSTRAINT event_session_unique UNIQUE (event_id, starts_at)
);

CREATE INDEX idx_event_session_starts_at ON event_session (starts_at);

-- Реакция привязана к мероприятию, а не к сеансу: иначе дизлайкнутый спектакль
-- вернётся в ленту ещё раз с каждой следующей датой.
CREATE TABLE reaction (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    event_id   BIGINT      NOT NULL REFERENCES event_item (id) ON DELETE CASCADE,
    session_id BIGINT      REFERENCES event_session (id) ON DELETE SET NULL,
    kind       VARCHAR(16) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT reaction_unique_per_event UNIQUE (user_id, event_id)
);

-- Уникальный индекс — и есть механизм идемпотентности списания.
-- Повторный callback ловится констрейнтом, а не проверкой "а не было ли уже".
CREATE TABLE purchase (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    session_id BIGINT      NOT NULL REFERENCES event_session (id),
    price_rub  INTEGER     NOT NULL,
    cinema     BOOLEAN     NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT purchase_unique_per_session UNIQUE (user_id, session_id)
);

CREATE TABLE metro_station (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(128)     NOT NULL UNIQUE,
    lat  DOUBLE PRECISION NOT NULL,
    lon  DOUBLE PRECISION NOT NULL,
    CONSTRAINT metro_lat_greater_than_lon CHECK (lat > lon)
);
